// <auto-generated />
namespace GatepassMonitoring.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedDataAnnotationsToProjectAndCheckerBodegeroNModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedDataAnnotationsToProjectAndCheckerBodegeroNModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202001200210344_AddedDataAnnotationsToProjectAndCheckerBodegeroNModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
