// <auto-generated />
namespace GatepassMonitoring.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ConfiguredDBGatepass2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfiguredDBGatepass2));
        
        string IMigrationMetadata.Id
        {
            get { return "202001140742337_ConfiguredDBGatepass2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
